name: Bug Report
description: Use this form to report a bug
labels: ["bug", "submitted issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
  - type: markdown
    attributes:
      value: "## Objective"
  - type: textarea
    id: objective
    attributes:
      label: "Objective"
      placeholder: "Clearly state what this bug report aims to achieve."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Detailed Description"
  - type: textarea
    id: detailed-description
    attributes:
      label: "Detailed Description"
      placeholder: "Provide a more detailed description of the bug."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Background"
  - type: textarea
    id: background
    attributes:
      label: "Background"
      placeholder: "Provide any relevant background information."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## User Impact"
  - type: textarea
    id: user-impact
    attributes:
      label: "User Impact"
      placeholder: "Describe how this bug affects users."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Steps to Reproduce"
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      placeholder: "List the steps to reproduce the behavior."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Acceptance Criteria"
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      placeholder: "List the conditions that signify that the bug has been fixed."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Technical Considerations"
  - type: textarea
    id: technical-considerations
    attributes:
      label: "Technical Considerations"
      placeholder: "Describe any technical considerations like architecture changes, dependencies, or database modifications."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Additional Context"
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      placeholder: "Include any other context or information that could be useful."
    validations:
      required: false
