name: JSON API - Issue Form
description: Submit an issue discovered in JSON API testing
title: "[JSON API]: "
labels: ["bug", "JSON API"]
assignees:
  - "reese-allison"
body:
  - type: input
    id: url
    attributes:
      label: Please paste URL where issue occured.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: checkboxes
    id: production
    attributes:
      label: Does this issue exist in Production?
      description: You may select more than one.
      options:
        - label: "Yes"
        - label: "No"
  - type: textarea
    id: error_message
    attributes:
      label: Relevant Error Message
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: contact
    attributes:
      label: Who are you?
    validations:
      required: true

