name: Chore Issue
description: Use this form to propose a chore
labels: ["chore", "proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: objective
  attributes:
    label: "Objective"
    placeholder: "State the reason for this chore and what it aims to achieve."
  validations:
    required: true

- type: textarea
  id: detailed-description
  attributes:
    label: "Detailed Description"
    placeholder: "Elaborate on what the chore entails."
  validations:
    required: true

- type: textarea
  id: acceptance-criteria
  attributes:
    label: "Acceptance Criteria"
    description: "List the conditions that signify that the chore has been completed successfully."
    value: "- [ ] <some given context or precondition>, <when I take this action>, <then this will be the result>"
  validations:
    required: true

- type: textarea
  id: technical-considerations
  attributes:
    label: "Technical Considerations"
    placeholder: "Are there any technical aspects to consider?"
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: "Additional Context"
    placeholder: "Add any other context or notes you have regarding this chore."
  validations:
    required: false

- type: textarea
  id: relevant_dependencies
  attributes:
    label: "Relevant Dependencies"
    description: "Include any relevant dependencies, i.e. issues, pull requests, branches."
  validations:
    required: false
