name: Form - Discovery Issue
description: Use this form to submit a discovery issue
labels: ["discovery", "proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: objective
  attributes:
    label: "Objective"
    description: "Briefly describe what this discovery issue aims to achieve."
  validations:
    required: true

- type: textarea
  id: background
  attributes:
    label: "Background"
    description: "Provide any background information that would help in the discovery process."
  validations:
    required: false

- type: textarea
  id: scope
  attributes:
    label: "Scope"
    description: "Define the scope of this discovery. What is in scope and what is out of scope?"
  validations:
    required: true

- type: textarea
  id: questions-to-answer
  attributes:
    label: "Questions to Answer"
    description: "List the questions that this discovery aims to answer."
  validations:
    required: true

- type: textarea
  id: findings
  attributes:
    label: "Findings"
    description: "Describe how the findings of this discovery phase should be delivered, e.g., detailed comments on issue, a proof-of-concept PR, etc."
  validations:
    required: false

- type: textarea
  id: acceptance-criteria
  attributes:
    label: "Acceptance Criteria"
    description: "List the conditions that signify this discovery is complete."
    value: "- [ ] Criterion 1\n- [ ] Criterion 2\n- [ ] Criterion 3"
  validations:
    required: true

- type: textarea
  id: stakeholders
  attributes:
    label: "Stakeholder(s)"
    description: "Who decides the Acceptance Criteria have been met."
    placeholder: "@moonryay @reese-allison @thephysicsriot @abhaykhu"
  validations:
    required: false

- type: textarea
  id: resources
  attributes:
    label: "Resources"
    description: "List any resources that could aid in the discovery process."
  validations:
    required: false

- type: textarea
  id: related-issues
  attributes:
    label: "Related Issues"
    description: "Link to any related issues or discovery phases."
  validations:
    required: false
