name: Feature Request
description: Use this form to submit a feature request
labels: ["enhancement", "proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: objective
  attributes:
    label: "Objective"
    description: "Clearly state what this feature aims to achieve."
  validations:
    required: true

- type: textarea
  id: detailed-description
  attributes:
    label: "Detailed Description"
    description: "Provide a more detailed description of the feature."
  validations:
    required: true

- type: textarea
  id: user-impact
  attributes:
    label: "User Impact"
    description: "Describe how users will benefit from this feature."
  validations:
    required: false

- type: textarea
  id: user-stories
  attributes:
    label: "User Stories"
    description: "List the user stories that this feature aims to fulfill."
    placeholder: "- [ ] As a [type of user], I want [an action] so that [benefit/value].\n- [ ] As a [type of user], I want [an action] so that [benefit/value].\n- [ ] As a [type of user], I want [an action] so that [benefit/value]."
  validations:
    required: false

- type: textarea
  id: acceptance-criteria
  attributes:
    label: "Acceptance Criteria"
    description: "List the conditions that signify the feature request has been fulfilled."
    value:"- [ ] Criterion 1\n- [ ] Criterion 2\n- [ ] Criterion 3"
  validations:
    required: true

- type: textarea
  id: technical-considerations
  attributes:
    label: "Technical Considerations"
    description: "Describe any technical considerations like architecture changes, dependencies, or database modifications."
  validations:
    required: false

- type: textarea
  id: mockups-or-examples
  attributes:
    label: "Mockups or Examples"
    description: "Include any mockups, diagrams, or examples that help illustrate the feature."
  validations:
    required: false

- type: textarea
  id: stakeholders
  attributes:
    label: "Stakeholders"
    description: "List the people or teams who have a vested interest in the successful completion of this feature."
  validations:
    required: false

- type: dropdown
  id: customer-team-impact
  attributes:
    label: "Customer / Team Impact"
    description: "Specify the impact of this feature."
    options:
      - "High"
      - "Medium"
      - "Low"

- type: textarea
  id: additional-context
  attributes:
    label: "Additional Context"
    description: "Include any other context or information that could be useful."
  validations:
    required: false
