name: Form - Bug Issue
description: Use this form to report a bug
labels: ["bug", "proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: background
  attributes:
    label: "Background"
    placeholder: "Provide any relevant background information."
  validations:
    required: false

- type: textarea
  id: detailed-description
  attributes:
    label: "Detailed Description"
      placeholder: |
      Provide a more detailed description of the bug.
      Include steps to reproduce, expected vs. actual behavior, etc.
  validations:
    required: true

- type: textarea
  id: user-impact
  attributes:
    label: "User Impact"
    placeholder: "Describe how this bug affects users."
  validations:
    required: false

- type: dropdown
  id: customer-impact
  attributes:
    label: "Customer Impact"
    description: What is the level of impact on our clients?
    options:
      - "High"
      - "Medium"
      - "Low"
    default: 2
  validations:
    required: true

- type: dropdown
  id: team-impact
  attributes:
    label: "Team Impact"
    description: What is the level of impact on our team?
    options:
      - "High"
      - "Medium"
      - "Low"

- type: dropdown
  id: in-production
  attributes:
    label: "Does this bug exist in production?"
    options:
    - "Yes"
    - "No"
    default: 0
  validations:
      required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: "Steps to Reproduce"
    placeholder: "List the steps to reproduce the behavior."
  validations:
    required: true

- type: textarea
  id: additional-context
  attributes:
    label: "Additional Context"
    placeholder: "Include any other context, information, or screenshots that could be useful."
  validations:
    required: false
