name: General Enhancement Issue
description: Use this form to propose a general enhancement
labels: ["enhancement", "proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: user-story
  attributes:
    label: "User Story"
    value: "As a user, I want to [...action...] so that I can [...goal/outcome...]"
  validations:
    required: true

- type: textarea
  id: background
  attributes:
    label: "Background"
    description: "What is the current behavior related to this enhancement? How is it insufficient for our users?"
  validations:
    required: true

- type: textarea
  id: ideal-solution
  attributes:
    label: "Ideal Solution"
    description: "What should users be able to do after this enhancement is finished? How does that solution satisfy their unmet needs?"
  validations:
    required: true

- type: textarea
  id: acceptance-criteria
  attributes:
    label: "Acceptance Criteria"
    description: "List the conditions that signify the feature request has been fulfilled."
    value: "- [ ] Criterion 1\n- [ ] Criterion 2\n- [ ] Criterion 3"
  validations:
    required: true

- type: textarea
  id: technical-considerations
  attributes:
    label: "Technical Considerations"
    description: "Describe any technical considerations like architecture changes, dependencies, or database modifications."
  validations:
    required: false

- type: textarea
  id: stakeholders
  attributes:
    label: "Stakeholders"
    description: "List the people or teams who have a vested interest in the successful completion of this feature."
  validations:
    required: false
