name: Development Task
description: Use this form to propose a general development task
labels: ["proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: detailed_description
  attributes:
    label: "Detailed Description"
    description: "Provide a detailed description of the task that has been identified."
  validations:
    required: true

- type: textarea
  id: task_requirements
  attributes:
    label: "Task Requirements"
    description: "List the conditions that signify the task has been fulfilled."
    value: "- [ ] Criterion 1\n- [ ] Criterion 2\n- [ ] Criterion 3"
  validations:
    required: true

- type: textarea
  id: stakeholders
  attributes:
    label: "Stakeholders"
    description: "List the people or teams who have a vested interest in the successful completion of this feature."
  validations:
    required: true
