name: Form - Bug Issue
description: Use this form to report a bug
labels: ["bug", "proposed issue"]
assignees: ["RyanEmslie"]
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: detailed-description
  attributes:
    label: "Detailed Description"
    description: "Provide a more detailed description of the bug."
  validations:
    required: true
    
- type: textarea
  id: reported_by
  attributes:
    label: "Reported By"
    description: "Who reported this issue? Was it the Product Support Team or a specific client?"
  validations:
    required: true

- type: textarea
  id: user-impact
  attributes:
    label: "User Impact"
    description: "Describe how this bug affects users."
  validations:
    required: false

- type: dropdown
  id: customer-impact
  attributes:
    label: "Customer Impact"
    description: What is the level of impact on our clients?
    options:
      - "High"
      - "Medium"
      - "Low"
  validations:
    required: true

- type: dropdown
  id: in-production
  attributes:
    label: "Does this bug exist in production?"
    options:
    - "Yes"
    - "No"
  validations:
      required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: "Steps to Reproduce"
    description: "List the steps to reproduce the behavior."
    value: "1. \n2. \n3"
  validations:
    required: true

- type: textarea
  id: expected_behavior
  attributes:
    label: "Expected Behavior"
    description: "Describe what should happen."
  validations:
    required: true

- type: textarea
  id: actual_behavior
  attributes:
    label: "Actual Behavior"
    description: "Describe what actually happens."
  validations:
    required: true

- type: textarea
  id: additional-context
  attributes:
    label: "Additional Context"
    description: "Include any other context, information, or screenshots that could be useful."
  validations:
    required: false
