name: Epic Issue
description: Use this form to create an epic
labels: ['epic', 'proposed epic']
projects: 'Feathr/projects/29'

body:
- type: textarea
  id: epic-description
  attributes:
    label: "Epic Description"
    description: "This issue groups issues that are related to..."
  validations:
    required: true

- type: textarea
  id: objective
  attributes:
    label: "Objective"
    description: "Clearly state what this epic aims to achieve. Include any key performance indicators (KPIs) if applicable."
  validations:
    required: true

- type: textarea
  id: background
  attributes:
    label: "Background Information"
    description: "Provide any background information that could help understand the scope and context of this epic."
  validations:
    required: ture

- type: textarea
  id: background-problem
  attributes:
    label: "Background Problem"
    description: "Describe the background problem."
  validations:
    required: true

- type: textarea
  id: case
  attributes:
    label: "Case"
    description: "Example of problem."
  validations:
    required: false

- type: textarea
  id: solution
  attributes:
    label: "Solution"
    description: "Broad parameters of the solution."
  validations:
    required: false

- type: textarea
  id: open-questions
  attributes:
    label: "Open Questions"
    description: "Anything that is still unclear and needs further discovery and decision making by the working pod."
  validations:
    required: false

- type: textarea
  id: user-stories
  attributes:
    label: "User Stories"
    description: "List the user stories that make up this epic, if applicable."
    value: "- [ ] As a [type of user], I want [an action] so that [benefit/value]."
  validations:
    required: true

- type: textarea
  id: tasks
  attributes:
    label: "Tasks"
    description: "List the tasks that need to be completed to close this epic."
    value: "- [ ] Task 1: [Briefly describe the task] (#IssueLink)\n- [ ] Task 2: [Briefly describe the task] (#IssueLink)\n- [ ] Task 3: [Briefly describe the task] (#IssueLink)"
  validations:
    required: true

- type: textarea
  id: acceptance-criteria
  attributes:
    label: "Acceptance Criteria"
    description: "Criteria that must be fulfilled for the epic to be considered complete."
    values: "- [ ] Criterion 1\n- [ ] Criterion 2\n- [ ] Criterion 3" 
  validations:
    required: true

- type: textarea
  id: success-metrics
  attributes:
    label: "Success Metrics"
    description: "The measurable way in which this feature will improve the lives of customers."
  validations:
    required: false
