name: JSON API - Issue Form
description: Submit an issue discovered in JSON API testing
title: "[JSON API]: "
labels: ["JSON API"]
assignees:
  - "reese-allison"
body:
  - type: input
    id: url
    attributes:
      label: Please paste URL where issue occurred.
    validations:
      required: true
  - type: input
    id: app_section
    attributes:
      label: What section of the App or Campaign type?
      description: i.e. Partner Message or Meta Retargeting
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue.
      description: Also tell us, what did you expect to happen? Attach screenshots if helpful.
    validations:
      required: true
  - type: dropdown
    id: in_production
    attributes:
      label: Does this error appear in production?
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  - type: textarea
    id: error_message
    attributes:
      label: Relevant Error Message
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

